# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: make
  displayName: 'Run a one-line script'

- task: CopyFiles@2
  inputs:
    contents: '**\*openjdk*.ipk'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'RoboRIOJRE'
